// <auto-generated />
using ClassInfoControll.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClassInfoControll.Migrations
{
    [DbContext(typeof(ScheduleContext))]
    [Migration("20240309140526_InitialCreateSQLite")]
    partial class InitialCreateSQLite
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.27");

            modelBuilder.Entity("ClassInfoControll.Models.ScheduleItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AlmUsage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClassTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FacultyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SyllabusAvailability")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Teacher")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ScheduleItems");
                });

            modelBuilder.Entity("ClassInfoControll.Models.ScheduleItem", b =>
                {
                    b.OwnsOne("ClassInfoControll.Models.StudentAttendance", "StudentAttendance", b1 =>
                        {
                            b1.Property<int>("ScheduleItemId")
                                .HasColumnType("INTEGER");

                            b1.Property<double>("AttendanceRate")
                                .HasColumnType("REAL");

                            b1.Property<int>("PresentStudents")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("TotalStudents")
                                .HasColumnType("INTEGER");

                            b1.HasKey("ScheduleItemId");

                            b1.ToTable("StudentAttendances");

                            b1.WithOwner()
                                .HasForeignKey("ScheduleItemId");
                        });

                    b.Navigation("StudentAttendance")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
